version: "3"

services:
  web:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/var/app
  db:
    image: postgres:16-alpine3.20
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432" 